[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.test]
command = "wasm-pack"
args = ["test", "--headless", "--chrome", "--firefox"]
