[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run]
workspace = false
dependencies = ["build_all_flow", "run_scheduler"]

[tasks.build]
workspace = false
dependencies = ["build_all_flow", "build_scheduler"]

[tasks.build_scheduler]
script = '''
cd beacon_dao-scheduler && wasm-pack build --target web --features wasm --release --features module
'''

[tasks.run_scheduler]
script = '''
cd beacon_dao-scheduler && cargo run --features cli
'''

[tasks.build_all_flow]
run_task = { name = "build_all", fork = true }

[tasks.build_all]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release", "--features", "module"]

[tasks.test]
command = "wasm-pack"
args = ["test", "--headless", "--firefox"]

[tasks.update]
run_task = { name = "update_all", fork = true }

[tasks.update_all]
script = '''cargo update'''