/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ideaSol from "./Idea.sol";
export type { ideaSol };
import type * as propSol from "./Prop.sol";
export type { propSol };
import type * as recoveryGroupSol from "./RecoveryGroup.sol";
export type { recoveryGroupSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Proposal } from "./Proposal";
export type { User } from "./User";
