name: Deployment
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: cargo install cargo-make
      - run: cargo +nightly install --git https://github.com/Vision-DAO/beacon-dao-factory
      - run: cd fixtures/modules && echo -n "export ARB_DEPLOYED=" > deployed
      - run: cd fixtures/modules && cargo make build
      - run: cd fixtures/modules && DEPLOYMENT_PRIVATE_KEY=${{ secrets.DEPLOYMENT_PRIVATE_KEY }} daowiz new beacon_dao-scheduler/pkg/beacon_dao_scheduler.js beacon_dao-scheduler/pkg/beacon_dao_scheduler_bg.wasm --eth-rpc-uri https://endpoints.omniatech.io/v1/arbitrum/one/public --contracts-dir ../../artifacts --eth-chain-id 42161 --ipfs-rpc-uri http://localhost:5001  >> deployed
      - run: cd fixtures/modules && source ./deployed && git clone git@github.com:Vision-DAO/beacon-dao-loader.git
      - run: cd beacon-dao-loader && yarn build && ipfs add -r .
